[project]
name = "example"
version = "0.1.0"
requires-python = ">=3.14"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["the_project"]

[project.scripts]
hello = "the_project:hello"

